; Regression testing for PLC Interpreter

(define run-regression-tests
	(lambda ()
		(begin
			(load "chez-init.ss")
			(load "17.ss")
			(load "Test 13.ss")
			(newline)
			(display "Assignment 13:")
			(newline)
			(r)
			(load "Test 14.ss")
			(newline)
			(display "Assignment 14:")
			(newline)
			(r)
			(load "Test 16.ss")
			(newline)
			(display "Assignment 16:")
			(newline)
			(r)
			(load "Test 17.ss")
			(newline)
			(display "Assignment 17:")
			(newline)
			(r)
		)
	)
)